### PR TITLE
define dynamic parameters to setup the rendering

### PR DESCRIPTION
**Pull request by doudou**
In particular, to change colors

This adds interactive tests for the visualization

### CODE REVIEW

**Comment by renan028** [comment]
All tests passed.
Is it possible to test the setGlareAttenuation ?

**Comment by doudou** [comment]
Glare is disabled by default, and I didn't want to get into figuring out what it was doing ... so didn't add the test for it. Is that acceptable you think ?

**Comment by elael** [comment]
Tests look ok, but I get many of those:

> PNG lib warning : iCCP: known incorrect sRGB profile
> PNG lib warning : iCCP: known incorrect sRGB profile
> PNG lib warning : iCCP: known incorrect sRGB profile
> PNG lib warning : iCCP: known incorrect sRGB profile
> QVariant type 84 with name uwAttenuation is not supported by the QtPropertyBrowser.

**Comment by renan028** [comment]
> Glare is disabled by default, and I didn't want to get into figuring out what it was doing ... so didn't add the test for it. Is that acceptable you think ?

Yes. I tried to change it but I didn't see any difference also.

**Pull request merged**
